### ISSUE TITLE
Add model segmentation args to schema

### ISSUE THREAD

**Issue by janjaapbos** [AlecAivazis/nautilus#45]
Limiting the result to e.g the first 5 does not work.

E.g. query {
recipes (first: 5) {
  edges {
    node {
      id
      name
    }
  }
  pageInfo {
    hasPreviousPage
    startCursor
    endCursor
    hasNextPage
  }
}}

returns the following error:

{
  "errors": [
    {
      "locations": [
        {
          "column": 8,
          "line": 15
        }
      ],
      "message": "[{'locations': [{'column': 25, 'line': 3}], 'message': 'Unknown argument \"first\" on field \"all_models\" of type \"Query\".'}]"
    }
  ],
  "data": {
    "recipes": null
  }
}

**Comment by janjaapbos** [comment]
Same error with e.g. 

query {
  recipes (before: "UmVjaXBlOjU=") {
  edges {
    node {
      id
      name
    }
  }
  pageInfo {
    hasPreviousPage
    startCursor
    endCursor
    hasNextPage
  }
}}

**Comment by AlecAivazis** [comment]
Thanks for pointing this out. Unfortunately, the arguments that are automatically generated do not yet include that kind of segmentation yet (I would love it to, though). If you wanted to add them, it should be pretty easy. The arguments that are generated for a model are defined [here](https://github.com/AlecAivazis/nautilus/blob/master/nautilus/api/filter/helpers.py#L7) and the way they are handled/applied is defined [here](https://github.com/AlecAivazis/nautilus/blob/master/nautilus/api/filter/helpers.py#L38).

**Comment by janjaapbos** [comment]
Thank you. I'll have a look at it.

2016-03-16 21:20 GMT+01:00 Alec Aivazis <notifications@github.com>:

**Comment by AlecAivazis** [comment]
What would be great is if we could get feature parity with whatever relay requires as well as [django-filter](https://github.com/carltongibson/django-filter). This is something I was thinking about contributing back to graphene's sqlalchemy support since they already support similar functionality in django projects

**Comment by janjaapbos** [comment]
Perhaps we can use some of this:
https://github.com/mitsuhiko/sqlalchemy-django-query

I guess we only support queries on the same model and no joins across different models? What would be the GraphQL way / standard? Only on the primary model and not further into referred / included models?

**Comment by AlecAivazis** [comment]
Yea that looks like a good way to save some work. Being able to filter on joins would be really cool but definitely not necessary. In order to integrate this, you probably want to import the _underscore_operators and add each to the args function I pointed out above. Also, unless i'm missing something, the query mixin should be added to all nautilus models by default, do you agree?

**Comment by janjaapbos** [comment]
Yes, all models could use it.

2016-03-19 17:17 GMT+01:00 Alec Aivazis <notifications@github.com>:

**Comment by AlecAivazis** [comment]
cool - if you have some time to look into this integration that would be great! If not, I can try to get to it sometime this week. I'm getting very close to a working solution for resolving a graphql schema using amqp and should have a PR by the end of the weekend.

**Comment by janjaapbos** [comment]
Thank you! I will try it and let you know.

2016-03-19 17:52 GMT+01:00 Alec Aivazis <notifications@github.com>:
